apiVersion: v1
kind: Service
metadata:
  name: exercise1-service
spec:
  selector:
    app: exercise1-deployment
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 80
    port: 8080
    nodePort: 31080
